# Generated by Django 5.2.1 on 2025-05-12 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tombo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField()),
                ('local_oficial', models.CharField(max_length=255)),
                ('caracteristicas', models.TextField(blank=True)),
                ('local_atual', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('localizado', 'Localizado'), ('nao_localizado', 'Não Localizado')], default='nao_localizado', max_length=15)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_anterior', models.CharField(max_length=100)),
                ('novo_local', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.responsavel'),
        ),
        migrations.CreateModel(
            name='ItemNaoEncontrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_trabalho', models.CharField(max_length=255)),
                ('tombo', models.CharField(max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tombo', 'local_trabalho')},
            },
        ),
    ]
